[phases.setup]
nixPkgs = ["nodejs-22_x", "pnpm"]

[phases.build]
cmds = [
    "pnpm --prefix backend install",
    "pnpm --prefix backend run build" 
]

[start]
cmd = "pnpm --prefix backend run start:prod"