version: '3.8'

services:
  backend:
    build:
      context: .
      dockerfile: ./Dockerfile
    container_name: netflix-backend
    ports:
      - '3001:3001'
    env_file:
      - .env
    restart: unless-stopped
